version: "3"

# This docker-compose file overrides the orchestrator service to specify the flag to test performance of cctxs
# and skip the regular tests

services:
  orchestrator:
    entrypoint: ["/work/start-zetae2e.sh", "local --test-performance"]

