version: '3.8'
services:
  zetachain_mainnet_rpc:
    platform: linux/amd64
    #This will build the binary from the GIT_REF you are locally on.
#    build:
#      context: ../../..
#      dockerfile: Dockerfile
    image: zetachain/zetacored:${DOCKER_TAG:-ubuntu-v14}
    environment:
      DAEMON_HOME: "/root/.zetacored"
      NETWORK: athens3
      #RESTORE_TYPE=snapshot/snapshot-archive/statesync
      RESTORE_TYPE: "snapshot"
      SNAPSHOT_API: https://snapshots.zetachain.com
      TRUST_HEIGHT_DIFFERENCE_STATE_SYNC: 40000
      CHAIN_ID: "athens_7001-1"
      VISOR_NAME: "cosmovisor"
      DAEMON_NAME: "zetacored"
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "false"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
      UNSAFE_SKIP_BACKUP: "true"
      CLIENT_DAEMON_NAME: "zetaclientd"
      CLIENT_DAEMON_ARGS: ""
      CLIENT_SKIP_UPGRADE: "true"
      CLIENT_START_PROCESS: "false"
      MONIKER: local-test
      RE_DO_START_SEQUENCE: "false"
    ports:
      - "26656:26656"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
      - "26657:26657"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - zetacored_data:/root/.zetacored/
    entrypoint: bash /scripts/start-zetae2e.sh

volumes:
  zetacored_data:
