name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check for CHANGELOG.md changes
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
      run: |
        git fetch origin ${{ github.base_ref }}
        CHANGELOG_DIFF=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- changelog.md)
        echo "${CHANGELOG_DIFF}"
        if [ -z "$CHANGELOG_DIFF" ]; then
          echo "ERROR: No changes detected in CHANGELOG.md. Please update the changelog."
          exit 1
        else
          echo "CHANGELOG.md has been updated."
        fi
